[package]
name = "jtd-fuzz"
version = "0.1.1"
authors = ["JSON Typedef Contributors"]
edition = "2018"

[dependencies]
anyhow = "^1"
jtd_fuzz = { path = "../" }
clap = "^2"
serde_json = "^1"
jtd = "^0.1.4"
rand_pcg = "^0.2"
rand = "^0.7"
