on:
  push:
    tags:
      - v*

jobs:
  publish_crate:
    runs-on: ubuntu-latest
    steps:
      - run: cargo publish

  create_release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}

  release_binary:
    runs-on: ${{ matrix.runs_on }}
    needs: create_release
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
          - x86_64-apple-darwin
          - x86_64-pc-windows-gnu
        include:
          - target: x86_64-unknown-linux-gnu
            runs_on: ubuntu-latest
            artifact: jtd-fuzz
          - target: x86_64-unknown-linux-musl
            runs_on: ubuntu-latest
            artifact: jtd-fuzz
          - target: x86_64-apple-darwin
            runs_on: macos-latest
            artifact: jtd-fuzz
          - target: x86_64-pc-windows-gnu
            runs_on: ubuntu-latest
            artifact: jtd-fuzz.exe
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo install cross
      - run: cross build --release --target=$TARGET
        env:
          TARGET: ${{ matrix.target }}
      - run: zip --junk-paths $TARGET.zip target/$TARGET/release/$ARTIFACT
        env:
          TARGET: ${{ matrix.target }}
          ARTIFACT: ${{ matrix.artifact }}
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ${{ matrix.target }}.zip
          asset_name: ${{ matrix.target }}.zip
          asset_content_type: application/zip
